# Generated by Django 5.2 on 2025-04-15 17:55

import local.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='DDD',
            field=models.CharField(max_length=3, validators=[local.models.validate_ddd]),
        ),
        migrations.AlterField(
            model_name='estado',
            name='uf',
            field=models.CharField(max_length=2, validators=[local.models.validate_uf]),
        ),
        migrations.AlterField(
            model_name='pais',
            name='DDI',
            field=models.CharField(max_length=2, validators=[local.models.validate_ddi]),
        ),
        migrations.AlterField(
            model_name='pais',
            name='sigla',
            field=models.CharField(max_length=3, validators=[local.models.validate_sigla]),
        ),
    ]
