# Generated by Django 5.2 on 2025-04-15 19:54

import local.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_alter_cidade_ddd_alter_estado_uf_alter_pais_ddi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoPagamento',
            fields=[
                ('id_condicao', models.AutoField(primary_key=True, serialize=False)),
                ('condicao', models.CharField(max_length=30, unique=True)),
                ('parcelas', models.PositiveIntegerField()),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('multa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_condicao', models.CharField(max_length=1, validators=[local.models.validate_status])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ult_alteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condição de Pagamento',
                'verbose_name_plural': 'Condições de Pagamento',
                'ordering': ['id_condicao'],
            },
        ),
    ]
