# Generated by Django 5.2 on 2025-04-16 17:55

import django.db.models.deletion
import local.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_condicaopagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('status_cliente', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
                ('nome', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('apelido', models.CharField(blank=True, max_length=50, null=True)),
                ('rg', models.CharField(blank=True, max_length=30, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, validators=[local.models.validate_cpf])),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, validators=[local.models.validate_cnpj])),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.PositiveIntegerField()),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tipo_cliente', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], max_length=1)),
                ('data_ult_alteracao', models.DateTimeField(auto_now=True)),
                ('id_cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.cidade')),
                ('id_condicao_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='local.condicaopagamento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('status_fornecedor', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
                ('nome_fantasia', models.CharField(max_length=100, unique=True)),
                ('razao_social', models.CharField(max_length=100)),
                ('data_fundacao', models.DateField(blank=True, null=True)),
                ('insc_municipal', models.CharField(blank=True, max_length=50, null=True)),
                ('insc_estadual', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, validators=[local.models.validate_cpf])),
                ('rg', models.CharField(blank=True, max_length=30, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, validators=[local.models.validate_cnpj])),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.PositiveIntegerField()),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('tipo_fornecedor', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ult_alteracao', models.DateTimeField(auto_now=True)),
                ('id_cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.cidade')),
                ('id_condicao_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='local.condicaopagamento')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['id_fornecedor'],
            },
        ),
    ]
