# Generated by Django 5.2 on 2025-04-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_cliente_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('status_cargo', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
                ('cargo', models.CharField(max_length=100, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ult_alteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['id_cargo'],
            },
        ),
    ]
