# Generated by Django 5.2 on 2025-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
