# Generated by Django 5.2 on 2025-04-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0007_alter_userprofile_numero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
